name: meditation_app
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_snackbar_content: ^0.1.3
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  draggable_fab: ^0.1.4
  flashy_tab_bar2: ^0.0.4
  flutter_native_splash: ^2.2.10+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  syncfusion_flutter_calendar: ^26.1.42
  audioplayers: ^5.2.1
  carousel_slider: ^4.2.1
  record: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: false

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/flutter.png
  web: true
  android_12:
    image: assets/flutter.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/flutter.png
    - assets/logo.png
    - assets/calm.mp3
    - assets/meditation.json
